### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Brian-Pob** [Brian-Pob/sp-24-hci#9]
- [x] search page
	- [x] searching with tags
	- [x] searching with filters
- [x] events (event page and event component)
	- [x] format date and time
	- [x] format location
	- [x] add icons
	- [x] set maximum size for images
	- [x] set maximum size for individual event pages
	- [x] apply formatting changes to event component
- [x] accounts
	- [x] implement account creation
	- [x] implement per-account event registration
- [ ] implement back button
- [x] replace placeholder images with more realistic images
